spring:
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB



  datasource:
    username: root
    password: whr
    url: jdbc:mysql://127.0.0.1:3306/r_pan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans


swagger2:
  show: true
  group-name: ${spring.application.name}
  base-package: com.wuaro.pan
  title: r-pan-server docs
  description: r-pan-server docs
  terms-of-service-url: http://127.0.0.1:${server.port}
  contact-name: wuaro
  contact-url: https://wuaro.github.io/
  contact-email: 1139188981@qq.com
  version: 1.0